services:
  backend:
    image: 'safe_bike_backend:latest'
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
    - db
    environment:
      - POSTGRES_USER=server
      - POSTGRES_DB=safe_bike_db
      - POSTGRES_PORT=5432
      - POSTGRES_JDBC_URL=jdbc:postgresql://db:5432/safe_bike_db
      # TODO: create on startup
      - POSTGRES_PASSWORD=password
      - APP_DEVELOPMENT_PROFILE=TRUE
  db:
    image: 'postgres:13.1'
    container_name: db
    restart: always
    volumes:
      - "./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=safe_bike_db
